FROM debian:10-slim

RUN apt-get update && apt-get install -y wget bash curl procps

RUN wget -c https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64

RUN mv confd-0.16.0-linux-amd64 /usr/local/bin/confd && chmod +x /usr/local/bin/confd

RUN mkdir -p /etc/confd/{conf.d,templates}

COPY ./generic-template.tmpl /etc/confd/templates/generic.tmpl
COPY ./dynamic-config.toml /etc/confd/conf.d/

ENTRYPOINT ["confd"]

