---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hola
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::612427630422:role/us-east-1-prod-x-default-default-hola
automountServiceAccountToken: true
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hola
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hola
  template:
    metadata:
      labels:
        app: hola
    spec:
      serviceAccountName: hola
      securityContext:
        fsGroup: 65534
      containers:
      - name: hola
        image: 612427630422.dkr.ecr.us-east-1.amazonaws.com/sre/hola:4126453f
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: hola
        - secretRef:
            name: hola
---
