---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hola
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hola
  template:
    metadata:
      labels:
        app: hola
    spec:
      containers:
      - name: hola
        image: 612427630422.dkr.ecr.us-east-1.amazonaws.com/sre/hola:latest
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
---
