---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hola
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::612427630422:role/us-east-1-prod-x-default-default-hola
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola
  template:
    metadata:
      labels:
        app: hola
    spec:
      shareProcessNamespace: true
      serviceAccountName: hola
      securityContext:
        fsGroup: 65534
      containers:
      - name: hola
        image: 612427630422.dkr.ecr.us-east-1.amazonaws.com/sre/hola:1d4f0098
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: hola
        volumeMounts:
        - name: dynamic-config
          mountPath: /opt/hola/
          readOnly: true
      - name: confd
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        image: 612427630422.dkr.ecr.us-east-1.amazonaws.com/sre/confd:1d4f0098
        imagePullPolicy: Always
        command: ["confd"]
        args: ["-backend", "consul", "-node", "http://consul.sre.svc.cluster.local:8500", "-interval", "10", "-watch"]
        volumeMounts:
        - name: dynamic-config
          mountPath: /opt/hola/
      volumes:
        - name: dynamic-config
          emptyDir: {}
---

