---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
      - name: hello-k8s
        image: 612427630422.dkr.ecr.us-east-1.amazonaws.com/sre/hello-kubernetes:latest
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
---

