---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hola
  annotations:
    kubernetes.io/ingress.class: internal-traefik
spec:
  rules:
  - host: hola.prod-us-east-1.moengage.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hola
          servicePort: http
---
