apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hola
  namespace: default
spec:
  encryptedData:
    foo: AgBSuEHYiOYywM6LeMvbot4M3QPA8Zu7r9l6Y7yuZGbsZe7k8+BB5qmREuZ05OgedMjSRaPrgmoBUlU3jqjkb7VXN4MjGqDuFFEBHCm+qc4foAGF+gwk9EcNZwzMUSkPOR8h7BncFns8IsXiIdeG7NVNZh2ygMIFbZvcYE0SfuiwZSYp4pGbVw7zRX5EC47XLfqUSNVR0NUJhfwFSSk/wbLqUoatUsxiqpHENsMGrlnrOnesKThHmexILi4F0scuE3ulVRo27jmjw8FoXtw3ZAeb9suEW4nLZJ2OBqFS1PSjJeLd+1p9CVQxB1t6tkWVlPFUw+gTE3d9s94L3oQvye878xS+Vs/bXh2B7hhv0IGVw+y6NfhcVNjxEyX+5EgHXpQTrgtIWT7LqHKcxRtIn51tl/mzVkjnniGub6dZR51C8kLHws6db+MemxJ1GRPBwOws8w5sp9fb7XowvGRXT47NfOwqesbGr/tfwRi11ojMSm1BOiv6yU5AXXktoerp5bf+NtSY8k+PsEIAKA1QvHVyo6SvmkxX4KAOsmoU9w9L9CLMgZnUv5hV8gYnerLBKkr+Z++YI5M5y3jqvsIaIdbAm59e/BB3IrJoRPTDfdwVGsSfccaEfyC9wPQM/Xunq2JUz5tp1JIYyvLbbyLo/gW/mW9Qnr4sQ3UVSRmCj+GMcasF7rvgXgdbq4auJ8WumUtlQHbjCw==
  template:
    metadata:
      creationTimestamp: null
      name: hola
      namespace: default
